import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>蜗牛问卷</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1>欢迎使用蜗牛问卷</h1>
        </div>

        <a
          href="https://github.com/qweijiaq"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            GitHub <span>-&gt;</span>
          </h2>
        </a>

        <a
          href="https://blog.wei-jia.top"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Blog <span>-&gt;</span>
          </h2>
        </a>

        <a
          href="https://page.wei-jia.top/"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Page <span>-&gt;</span>
          </h2>
        </a>

        <a
          href="https://woniu.blog.csdn.net/"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            CSDN <span>-&gt;</span>
          </h2>
        </a>
      </main>
    </>
  );
}
